SELECT ITEM_ID, ITEM_NAME, RARITY 
FROM ITEM_INFO
WHERE ITEM_NAME NOT IN 
(SELECT II.ITEM_NAME
FROM ITEM_TREE IT LEFT JOIN ITEM_INFO II ON IT.PARENT_ITEM_ID = II.ITEM_ID
WHERE II.ITEM_NAME IS NOT NULL)
ORDER BY 1 DESC