-- 코드를 입력하세요
WITH RE_PURCHASED AS (
    SELECT USER_ID, PRODUCT_ID, COUNT(PRODUCT_ID) AS CNT_PURCHASED
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
)
SELECT USER_ID, PRODUCT_ID
FROM RE_PURCHASED
WHERE CNT_PURCHASED >= 2
ORDER BY 1,2 DESC
