-- 코드를 입력하세요
WITH JOIN_TABLE AS (
    SELECT AI.ANIMAL_ID, AI.NAME , DATEDIFF(AO.DATETIME,AI.DATETIME) AS INTAKE_DAY
    FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
)
SELECT ANIMAL_ID, NAME
FROM JOIN_TABLE
ORDER BY INTAKE_DAY DESC
LIMIT 2