-- 코드를 입력하세요
WITH BEST_FAVORITES AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO RI JOIN BEST_FAVORITES BF ON RI.FOOD_TYPE = BF.FOOD_TYPE AND RI.FAVORITES = BF.FAVORITES
ORDER BY 1 DESC