-- 코드를 입력하세요
WITH WRITE_MORE_THREE AS (
    SELECT WRITER_ID, COUNT(WRITER_ID) AS CNT_BOARD
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING CNT_BOARD >= 3
)
SELECT A.USER_ID, A.NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(A.TLNO,3), '-', SUBSTRING(A.TLNO,4,4), '-', SUBSTRING(A.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER A JOIN WRITE_MORE_THREE B ON A.USER_ID = B.WRITER_ID
ORDER BY 1 DESC