WITH IN_NOT_SPAYED AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
),
OUT_SPAYED AS (
    SELECT *
    FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE '%Neutered%' OR SEX_UPON_OUTCOME LIKE '%Spayed%'
)
SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM IN_NOT_SPAYED INS JOIN OUT_SPAYED OS ON INS.ANIMAL_ID = OS.ANIMAL_ID