SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT UI.USER_ID) AS USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID 
AND UI.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3