WITH ANIMAL_JOIN AS (
    SELECT AO.ANIMAL_ID, AO.NAME, AI.ANIMAL_ID AS AI_ANIMAL_ID
    FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
    HAVING AI_ANIMAL_ID IS NULL
)
SELECT ANIMAL_ID, NAME
FROM ANIMAL_JOIN 
ORDER BY 1