WITH 2021_JOIN_USER AS (
    SELECT USER_ID, JOINED
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
),
ALL_2021_JOIN_USER AS(
    SELECT COUNT(*) AS ALL_2021_JOIN_USER
    FROM 2021_JOIN_USER
), 
TOTAL_JOIN_TABLE AS(
    SELECT *
    FROM 2021_JOIN_USER JOIN ALL_2021_JOIN_USER
),
ONLINE_JOIN AS (
    SELECT OS.USER_ID, OS.SALES_DATE, TJT.ALL_2021_JOIN_USER, LEFT(OS.SALES_DATE,4) AS YEAR, SUBSTRING(OS.SALES_DATE, 6,2) AS MONTH, COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE OS JOIN TOTAL_JOIN_TABLE TJT ON OS.USER_ID = TJT.USER_ID  
    GROUP BY YEAR,MONTH
)
SELECT YEAR,MONTH,PURCHASED_USERS, ROUND(PURCHASED_USERS/ALL_2021_JOIN_USER,1) AS PURCHASED_RATIO
FROM ONLINE_JOIN
ORDER BY YEAR, MONTH