WITH RECURSIVE FamilyTree AS (
    
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    
    SELECT 
        E.ID,
        E.PARENT_ID,
        F.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E
    JOIN FamilyTree F
    ON E.PARENT_ID = F.ID
)

SELECT COUNT(GENERATION) AS COUNT, GENERATION
FROM FamilyTree
WHERE ID NOT IN (SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION