WITH CNT AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) > 1
)
SELECT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES JOIN CNT ON PLACES.HOST_ID = CNT.HOST_ID
ORDER BY 1