WITH table_car AS (
    SELECT a.*, b.HISTORY_ID, b.START_DATE, b.END_DATE
    FROM CAR_RENTAL_COMPANY_CAR a JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY b ON a.CAR_ID = b.CAR_ID
    WHERE a.CAR_TYPE = '트럭'
),
car_rent_date AS (
    SELECT *, (DATEDIFF(END_DATE, START_DATE) + 1) AS day_diff, 
    CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) >= 7 AND DATEDIFF(END_DATE, START_DATE) <= 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) >= 30 AND DATEDIFF(END_DATE, START_DATE) <= 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) >= 90 THEN '90일 이상'
    ELSE '7일 미만'
    END AS DURATION_TYPE
    FROM table_car
),
car_discount AS (
    SELECT c.*, IFNULL(d.DISCOUNT_RATE, 0) AS DISCOUNT_RATE
    FROM car_rent_date c LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN d ON c.DURATION_TYPE = d.DURATION_TYPE AND c.CAR_TYPE = d.CAR_TYPE
    GROUP BY HISTORY_ID
)
SELECT HISTORY_ID, ROUND(DAILY_FEE * day_diff * ((100-DISCOUNT_RATE)/100),0) AS FEE
FROM car_discount
ORDER BY FEE DESC, HISTORY_ID DESC