-- 코드를 입력하세요
WITH datetime_to_time AS (
    SELECT *, DATE_FORMAT(DATETIME,'%H') AS hour_only
    FROM ANIMAL_OUTS
), 
time_slots AS (
    SELECT 0 AS hour UNION ALL
    SELECT 1 UNION ALL
    SELECT 2 UNION ALL
    SELECT 3 UNION ALL
    SELECT 4 UNION ALL
    SELECT 5 UNION ALL
    SELECT 6 UNION ALL
    SELECT 7 UNION ALL
    SELECT 8 UNION ALL
    SELECT 9 UNION ALL
    SELECT 10 UNION ALL
    SELECT 11 UNION ALL
    SELECT 12 UNION ALL
    SELECT 13 UNION ALL
    SELECT 14 UNION ALL
    SELECT 15 UNION ALL
    SELECT 16 UNION ALL
    SELECT 17 UNION ALL
    SELECT 18 UNION ALL
    SELECT 19 UNION ALL
    SELECT 20 UNION ALL
    SELECT 21 UNION ALL
    SELECT 22 UNION ALL
    SELECT 23
)
SELECT ts.hour AS HOUR, COUNT(dtt.hour_only) AS COUNT
FROM time_slots ts LEFT JOIN datetime_to_time dtt ON dtt.hour_only = ts.hour
GROUP BY ts.hour
ORDER BY ts.hour