WITH GRD AS(
SELECT EMP_NO, AVG(SCORE) AS AVG_SCORE
FROM HR_GRADE
GROUP BY 1
)
SELECT EMP.EMP_NO, EMP.EMP_NAME, 
CASE WHEN GRD.AVG_SCORE >= 96 THEN 'S'
    WHEN GRD.AVG_SCORE >= 90 THEN 'A'
    WHEN GRD.AVG_SCORE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE,
CASE WHEN GRD.AVG_SCORE >= 96 THEN EMP.SAL * 0.20
    WHEN GRD.AVG_SCORE >= 90 THEN EMP.SAL * 0.15
    WHEN GRD.AVG_SCORE >= 80 THEN EMP.SAL * 0.10
    ELSE EMP.SAL * 0 END AS BONUS
FROM HR_EMPLOYEES EMP JOIN GRD ON GRD.EMP_NO = EMP.EMP_NO