WITH CNT_RENTAL_TABLE AS (
    SELECT *, COUNT(CAR_ID) AS CNT_RENTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01' AND START_DATE < '2022-11-01'
    GROUP BY CAR_ID
    HAVING CNT_RENTAL >= 5
)
SELECT MONTH(A.START_DATE) AS MONTH, A.CAR_ID, COUNT(A.CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN CNT_RENTAL_TABLE B ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE >= '2022-08-01' AND A.START_DATE < '2022-11-01'
GROUP BY MONTH, A.CAR_ID
HAVING RECORDS != 0
ORDER BY 1, 2 DESC