-- 코드를 작성해주세요

WITH DEV_SKILLS AS (
    SELECT D.ID,GROUP_CONCAT(S.NAME) AS SKILLS
    FROM DEVELOPERS D JOIN SKILLCODES S ON (D.SKILL_CODE & (S.CODE)) != 0
    GROUP BY D.ID
)
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEV_SKILLS DS JOIN DEVELOPERS D ON DS.ID = D.ID
WHERE DS.SKILLS LIKE ('%Python%') OR DS.SKILLS LIKE ('%C#')
ORDER BY 1