-- 코드를 작성해주세요

WITH DEV_SKILLS AS (
    SELECT D.ID, GROUP_CONCAT(S.NAME) AS SKILLS
    FROM DEVELOPERS D JOIN SKILLCODES S ON (D.SKILL_CODE & (S.CODE)) > 0
    GROUP BY D.ID
)
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D JOIN DEV_SKILLS DS ON DS.ID = D.ID
WHERE DS.SKILLS LIKE ('%Python%') OR DS.SKILLS LIKE ('%C#')
ORDER BY 1
