-- 코드를 입력하세요
SELECT B.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE B.CAR_TYPE = '세단' AND MONTH(A.START_DATE) = 10
GROUP BY B.CAR_ID
ORDER BY 1 DESC