WITH MAX_VIEWS AS (
    SELECT BOARD_ID, DENSE_RANK() OVER (ORDER BY VIEWS DESC) AS VIEW_RANK
    FROM USED_GOODS_BOARD
)
SELECT CONCAT('/home/grep/src/', UGF.BOARD_ID, '/', UGF.FILE_ID, UGF.FILE_NAME,UGF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE UGF JOIN MAX_VIEWS MV ON UGF.BOARD_ID = MV.BOARD_ID
WHERE MV.VIEW_RANK = 1
ORDER BY UGF.FILE_ID DESC