WITH selected_category as (
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY 1
    ORDER BY 2 DESC
)
SELECT SC.* , FP.PRODUCT_NAME
FROM selected_category SC INNER JOIN FOOD_PRODUCT FP ON SC.MAX_PRICE = FP.PRICE AND SC.CATEGORY = FP.CATEGORY
ORDER BY SC.MAX_PRICE DESC