-- 코드를 작성해주세요
WITH NULL_TO_TEN AS (
    SELECT *, IFNULL(LENGTH,10) AS LENGTH2 
    FROM FISH_INFO
),
FISH_TABLE AS (
    SELECT FISH_TYPE, (SUM(LENGTH2)/ COUNT(LENGTH2)) AS avg_length, COUNT(LENGTH2) AS FISH_COUNT, MAX(LENGTH2) AS MAX_LENGTH
    FROM NULL_TO_TEN
    GROUP BY FISH_TYPE
)
SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM FISH_TABLE
WHERE avg_length >= 33
ORDER BY FISH_TYPE